version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-ndk-r17b
    steps:
      - checkout
      # >>- run:
          # >>name: Initial Checkups
          # >>command: |
            # >>echo ">>> Early Disc Space is" && df -hlT
            # >>echo ">>> Free RAM Memory now?" && free -h
            # >>echo ">>> CPU Details?" && lscpu
            # >>echo ">>> System Info?" && uname -a
            # >>echo ">>> whoami?" && whoami
      - run:
          name: Setup the Environment by Akhilnarang's Scripts
          command: |
            # while sleep 180; do df -hlT; done & ./script.sh
            mkdir ~/Landroid && cd ~/Landroid
            mkdir toolz && cd toolz
            git clone https://github.com/akhilnarang/scripts
            cd scripts && bash setup/android_build_env.sh
            cd ../../ && rm -rf toolz
            sudo apt-get install -qqy wput
            echo ">>> Initial Disc Space is" && df -hlT
          no_output_timeout: 5m
      - run:
          name: Git Config and Get LineageOS
          command: |
            cd ~/Landroid
            # Github Authorization
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            # Initialize the repo data fetching
            repo init -q -u https://github.com/LineageOS/android.git -b cm-14.1 --depth 1
            # Add device sources in local_manifest
            wget -q 'https://gist.githubusercontent.com/rokibhasansagar/c65b9b7f9564bd9d70084c68719b292a/raw/18fff97243a7e4b7de476e47cc569c10ad8d1279/doogee_x5-local_manifest.xml' -P .repo/local_manifests
            # Sync it up!
            sudo repo sync -c -f -q --force-sync --no-clone-bundle --no-tags -j36
            # Own the files
            sudo chown -R circleci ~/Landroid/*
            # Patch
            cd device/doogee/x5/patches
            bash do.sh
            cd ~/Landroid
            # How much space is taken?
            echo ">>> How much space taken by .repo?" && du -sh .repo/
            echo ">>> How much space taken by checked-out files?" && du -sh ~/Landroid
            echo ">>> Primary Disc Space is now --- " && df -hlT
          no_output_timeout: 20m
      - run:
          name: Set 50 Gigs of CCache
          command: |
            echo "export USE_CCACHE=1" >> ~/.bashrc
            echo "export CCACHE_COMPRESS=1" >> ~/.bashrc
            echo "export ANDROID_JACK_VM_ARGS='-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G'" >> ~/.bashrc
            # >>echo "export USE_NINJA=false" >> ~/.bashrc
            . ~/.bashrc
            ccache -M 50G
            ccache -C
      - run:
          name: Build the LineageOS
          command: |
            cd ~/Landroid
            echo "Environment Setup"
            . build/envsetup.sh
            echo "Lunching --- "
            lunch lineage_x5-userdebug
            sleep 2
            echo "Brunching, Umm.. --- "
            brunch lineage_x5-userdebug
          no_output_timeout: 50m
      - run:
          name: Upload Resulting Files
          command: |
            cd ~/Landroid
            cd out/target/product/x5/
            # list all the files
            ls -la */
            # upload
            for file in *; do wput $file ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TestLAndroid/Doogee_X5/ ; done
          no_output_timeout: 10m
    branches:
      only:
        - master
